jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build and test
      run: ./gradlew clean ashley:test
    - continue-on-error: true
      id: import_gpg
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@1c6a9e9d3594f2d743f1b1dd7669ab0dfdffa922
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - continue-on-error: true
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      name: Release build deploy
      run: ./gradlew clean uploadArchives -PRELEASE=true -Psigning.gnupg.keyId=${{
        secrets.GPG_KEYID }} -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE
        }} -Psigning.gnupg.keyName=${{ secrets.GPG_KEYID }}
name: Compile and publish release
on:
  repository_dispatch:
    types: trigger-ga___publish_release.yml
